name: Auto Format Python

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  auto-format:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff isort black

      # Optional: Install system dependencies (only on Linux)
      # Wenn nicht unbedingt nötig, kann dieser Schritt auch deaktiviert werden.
      - name: Install system dependencies (only on Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libayatana-appindicator3-dev \
            libasound2-dev \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libxdo-dev \
            pkg-config \
            webkit2gtk-4.1

      - name: Run ruff (auto-fix)
        run: ruff check --fix .

      - name: Run isort (auto-fix)
        run: isort .

      - name: Run black (auto-fix)
        run: black .

      - name: Check for changes and push
        shell: bash
        run: |
          git diff
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code was reformatted. Committing changes..."
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "style: auto-format with ruff, isort, and black"
            git push
          else
            echo "No changes to commit."
          fi
