name: Lint PR

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff isort black

      - name: Install system dependencies (only on Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libayatana-appindicator3-dev \
            libasound2-dev \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libxdo-dev \
            pkg-config \
            webkit2gtk-4.1

      - name: Run Ruff linter (always green)
        run: |
          echo "Running Ruff linter..."
          ruff check . || true

      - name: Run isort linter (always green)
        run: |
          echo "Running isort linter..."
          isort --check-only --diff . || true

      - name: Run black linter (always green)
        run: |
          echo "Running black linter..."
          black --check . || true

      - name: Done
        run: echo "Linting complete! (No failure exit codes)"
