name: Rust CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  rust-check-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install system dependencies (for Rust build)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libayatana-appindicator3-dev \
            libasound2-dev \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libxdo-dev \
            pkg-config \
            webkit2gtk-4.1
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo check
        run: cargo check --all-targets --all-features

      - name: Run tests
        run: cargo test --all

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  rust-check-windows:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo check
        run: cargo check --all-targets --all-features

      - name: Run tests
        run: cargo test --all

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  rust-check-macos:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo check
        run: cargo check --all-targets --all-features

      - name: Run tests
        run: cargo test --all

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
